### PR TITLE
Added vec2 component

### PR DESCRIPTION
**Pull request by karai17**
Stylized code from HUMP.vector to suit mlib. Copyright and license left
in tact.

### CODE REVIEW

**Comment by karai17** [comment]
There are also more components from the CPML library on the @excessive page. I am personally not fond of mlib's style since you can't overload operators or the likes. I highly recommend checking out how CPML creates objects.

**Comment by davisdude** [comment]
Thanks for the pull request! Vectors are one of the reasons why I wanted to add objects to it, hence issue davisdude/mlib/issues/9

**Comment by karai17** [comment]
If I have time tomorrow (or remind me in IRC!) I'll take a look at
refactoring your codez.


---
Landon Manning
lmanning17@gmail.com

**Comment by davisdude** [comment]
Sounds good to me!
(I've been meaning to do do that for a while now, so any help would be welcome!)

**Pull request merged**
